input:
  - user_request:
      id: 0
      args:
        ingredients:
          - flour
          - sugar
          - eggs
        cooking_time: 30
        dietary_requirement:
          - vegetarian
          - gluten-free
        flavour_profile: "sweet"
resources:
  - recipe:
      id: 1

output:
  - recipe:
      id: 1
