input:
  - user_request:
      id: 0
      args:
        ingredients:
          - olive oil
          - flour
          - tomato
        cooking_time: 60
        dietary_requirement:
          - lactose free
        flavour_profile: "savoury"
resources:
  - recipe:
      id: 1

output:
  - recipe:
      id: 1
